### ISSUE TITLE
Conduct User testing with v6

### ISSUE THREAD

**Issue by designerzim** [sungry/CS177#101]
Using build 6, conduct user testing and report feedback gathered.

**Comment by angelsonly** [comment]
Liz feedback was:
1. She was looking in the direction of the character movement and therefore did not notice the instruction Press space to jump. It is blurred and faded and mixed with background. She advised put the instructions in the direction of the character movement.  
2. Her suggestion was - we should have given the second chance to our character.

**Comment by angelsonly** [comment]
She was pressing the arrow up to jump. It took her several times to figure it out.

**Comment by kokixi** [comment]
Write her feedback in the following document, so we have all feedbacks in one document
https://docs.google.com/document/d/1NzZgM7LR3sx_ktTKFAGxa4gonvQKLVN6XlmCV4ATTRI/edit

**Comment by angelsonly** [comment]
She also experienced the delay when she pressed Start button.

**Comment by angelsonly** [comment]
Veronila said:
1. It does take too long to start the game
2. She also did not see the sign "press space to jump".
3. She suggested - indicate when your level was increased. She noticed the speed increased but did not see the sign "Congratulation you are on level 2"
4. The character should have been given 3 chances. Because you just start and you die to fast.

**Comment by angelsonly** [comment]
She also mentioned to increase the number of enemies as you progress in the game.
